### ISSUE TITLE
Error since update

### ISSUE THREAD

**Issue by leafsfan525** [vorghahn/SSTV-PLEX-PLUGIN#3]
With the new update, I am getting an error trying to access the schedule/guide. It says "Provided guide files are invalid, missing or empty, check the log file for more information".

I am also not sure where to find the log file it is talking about.

**Comment by vorghahn** [comment]
PLEXHOMEDIR/Logs/PMS Plugins Logs/com.plexapp.plugins.smoothstreamstv.log
