### ISSUE TITLE
IOS Devices

### ISSUE THREAD

**Issue by ExeCuteUK** [vorghahn/SSTV-PLEX-PLUGIN#4]
Hi,

This seems to work great in the majority of devices, but streams are not playing on IOS devices or via Chromecast, Chrome & IE ?

Chrome / IE Spit out a Shakka network error.

Is there something I can do about this ? Or will you need logs to look into it ?

**Comment by vorghahn** [comment]
Logs generally, make sure you're not using RTMP on Apple gear.

**Comment by ExeCuteUK** [comment]
This was the answer. RTMP was not working on Apple. I switched to HLS and all OK. Only issue is it doesnt like FireTV/Stick very well now but works if i set it to transcode down.

Thanks
